### PR TITLE
added docker-compose.yml

### PR DESCRIPTION
**Pull request by theDepart3d**
- Added docker-compose file
- Updated Docker file and app location to provide a working docker-compose file
- Updated README to reflect docker-compose usage

### CODE REVIEW

**Comment by porjo** [comment]
Thanks for your interest in this project. I have a couple objections to this PR:
- the docker image should be pulled from GHCR by default. And will `docker-compose up` pull first if build is also specified?
- it's a minor thing, but binaries don't belong in `/etc`.

**Comment by theDepart3d** [comment]
> Thanks for your interest in this project. I have a couple objections to this PR.

No problem, I was about to make something of my own but i did a quick Github search and found yours to be perfect for my use case.

> the docker image should be pulled from GHCR by default. And will docker-compose up pull first if build is also specified?

This is how the docker-compose file actually works in this case:
First the user will clone the project, since docker is not actually needed and the project can be built using go. So what i have done is; The docker compose file will fetch the latest `golang:alpine`.
Then it executes the Dockerfile contents and quite literally it builds the project from the local files from the clone. So there is not need to pull it from any external sources as it builds everything locally except for pulling the latest go and alpine.

its just an easy solution. All the user has to do is clone the repo and execute `docker-compose up -d` and within a few seconds/minutes the project would be running.

 > it's a minor thing, but binaries don't belong in /etc

When i had it at /app for some reason it worked on one machine but a brand new lxc with docker it kept stating that it cannot `mkdir /app`. After changing the location to /etc/ it seemed to work flawlessly on all machines. Currently i tested it on 2 different LxC containers both brand new. Seemed to work universally. Give it a go and you will see the `docker-compose up -d` makes life a little bit easier for the end user.

**Comment by porjo** [comment]
> The docker compose file will fetch the latest `golang:alpine`. Then it executes the Dockerfile contents and quite literally it builds the project from the local files from the clone. So there is not need to pull it from any external sources as it builds everything locally except for pulling the latest go and alpine.

But it does pull from external sources. And if you're doing that, then you may aswell pull rumblerss from GHCR (ghcr.io/porjo/rumblerss:latest) and save yourself the build step.

> When i had it at /app for some reason it worked on one machine but a brand new lxc with docker it kept stating that it cannot `mkdir /app`. After changing the location to /etc/ it seemed to work flawlessly on all machines. 

That seems like an issue with your local environment. I've used `/app` for several projects and never had an issue.

Again, I do appreciate your interest but I'm going to close this PR now.

**Comment by theDepart3d** [comment]
You make a good point. Thanks for clearing that up. I'll make a new docker-compose with the image from ghcr.io instead :)

**Pull request closed without merging**
